[2024-11-08T08:56:12.238+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_csv_file.preprocess_data scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T08:56:12.276+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_csv_file.preprocess_data scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T08:56:12.277+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-08T08:56:12.329+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data> on 2024-11-07 00:00:00+00:00
[2024-11-08T08:56:12.339+0000] {standard_task_runner.py:60} INFO - Started process 199 to run task
[2024-11-08T08:56:12.347+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_csv_file', 'preprocess_data', 'scheduled__2024-11-07T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_csv_file.py', '--cfg-path', '/tmp/tmpqfmqytfb']
[2024-11-08T08:56:12.350+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask preprocess_data
[2024-11-08T08:56:12.494+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_csv_file.preprocess_data scheduled__2024-11-07T00:00:00+00:00 [running]> on host f66859b21ee4
[2024-11-08T08:56:12.667+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Satrio' AIRFLOW_CTX_DAG_ID='etl_csv_file' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-07T00:00:00+00:00'
[2024-11-08T08:56:12.765+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_csv_file.py", line 45, in preprocess_data
    df['Units Sold'] = df['Units Sold'].astype(int)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 105, in _astype_nansafe
    return _astype_float_to_int_nansafe(arr, dtype, copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 150, in _astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
[2024-11-08T08:56:12.826+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=etl_csv_file, task_id=preprocess_data, execution_date=20241107T000000, start_date=20241108T085612, end_date=20241108T085612
[2024-11-08T08:56:12.950+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task preprocess_data (Cannot convert non-finite values (NA or inf) to integer; 199)
[2024-11-08T08:56:13.028+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-08T08:56:13.148+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
