[2024-11-08T08:39:57.065+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_csv_file.read_local_csv manual__2024-11-08T08:39:52.819440+00:00 [queued]>
[2024-11-08T08:39:57.115+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_csv_file.read_local_csv manual__2024-11-08T08:39:52.819440+00:00 [queued]>
[2024-11-08T08:39:57.116+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-08T08:39:57.198+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_local_csv> on 2024-11-08 08:39:52.819440+00:00
[2024-11-08T08:39:57.233+0000] {standard_task_runner.py:60} INFO - Started process 216 to run task
[2024-11-08T08:39:57.250+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_csv_file', 'read_local_csv', 'manual__2024-11-08T08:39:52.819440+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_csv_file.py', '--cfg-path', '/tmp/tmp4_86kch5']
[2024-11-08T08:39:57.255+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask read_local_csv
[2024-11-08T08:39:57.397+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_csv_file.read_local_csv manual__2024-11-08T08:39:52.819440+00:00 [running]> on host ea0df5a66d62
[2024-11-08T08:39:57.698+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Satrio' AIRFLOW_CTX_DAG_ID='etl_csv_file' AIRFLOW_CTX_TASK_ID='read_local_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T08:39:52.819440+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T08:39:52.819440+00:00'
[2024-11-08T08:39:57.714+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_csv_file.py", line 30, in read_local_csv
    df = pd.read_csv(local_csv_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ThinkPad\\OneDrive - Bina Nusantara\\Documents\\Hacktiv8\\Milestone\\p2-ftds021-hck-m3-satriotn\\adidas_sales.csv'
[2024-11-08T08:39:57.743+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=etl_csv_file, task_id=read_local_csv, execution_date=20241108T083952, start_date=20241108T083957, end_date=20241108T083957
[2024-11-08T08:39:57.784+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task read_local_csv ([Errno 2] No such file or directory: 'C:\\Users\\ThinkPad\\OneDrive - Bina Nusantara\\Documents\\Hacktiv8\\Milestone\\p2-ftds021-hck-m3-satriotn\\adidas_sales.csv'; 216)
[2024-11-08T08:39:57.808+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-08T08:39:57.918+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
